fullnameOverride: orders

replicaCount: 1

profile: default

namespace: development

image:
  repository: acme
  tag: latest
  pullPolicy: Always

dockerRegistrySecret: regcred

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8082
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: orders
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  # hosts:
  #   - sockshop-orders.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels: {}

autoscaling:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 1
    memory: 1252Mi

readinessProbe:
  httpGet:
    path: /health
    port: 8082
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /health
    port: 8082
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 15
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 8080
#   initialDelaySeconds: 15
#   periodSeconds: 10

# hostNetwork: true
# dnsPolicy: Default

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: ZIPKIN
    value: zipkin.jaeger.svc.cluster.local
  - name: JAVA_OPTS
    value: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

configmap:
  enabled: false
  data: {}
    # MESSAGE: "hello world"

secret:
  enabled: false
  data: {}
    # SECRET: "c2VjcmV0IHdvcmxkCg=="
